# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagroom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagroom
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  target 'InstagroomTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstagroomUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
